export const ADMIN_EMPLOYEES_REQUEST = 'ADMIN_EMPLOYEES_REQUEST'
export const ADMIN_EMPLOYEES_SUCCESS = 'ADMIN_EMPLOYEES_SUCCESS'
export const ADMIN_EMPLOYEES_FAIL = 'ADMIN_EMPLOYEES_FAIL'

export const ALL_EMPLOYEES_REQUEST = 'ALL_EMPLOYEES_REQUEST'
export const ALL_EMPLOYEES_SUCCESS = 'ALL_EMPLOYEES_SUCCESS'
export const ALL_EMPLOYEES_FAIL = 'ALL_EMPLOYEES_FAIL'

export const NEW_EMPLOYEE_REQUEST = 'NEW_EMPLOYEE_REQUEST'
export const NEW_EMPLOYEE_SUCCESS = 'NEW_EMPLOYEE_SUCCESS'
export const NEW_EMPLOYEE_RESET = 'NEW_EMPLOYEE_RESET'
export const NEW_EMPLOYEE_FAIL = 'NEW_EMPLOYEE_FAIL'

export const DELETE_EMPLOYEE_REQUEST = 'DELETE_EMPLOYEE_REQUEST'
export const DELETE_EMPLOYEE_SUCCESS = 'DELETE_EMPLOYEE_SUCCESS'
export const DELETE_EMPLOYEE_RESET = 'DELETE_EMPLOYEE_RESET'
export const DELETE_EMPLOYEE_FAIL = 'DELETE_EMPLOYEE_FAIL'

export const UPDATE_EMPLOYEE_REQUEST = 'UPDATE_EMPLOYEE_REQUEST'
export const UPDATE_EMPLOYEE_SUCCESS = 'UPDATE_EMPLOYEE_SUCCESS'
export const UPDATE_EMPLOYEE_RESET = 'UPDATE_EMPLOYEE_RESET'
export const UPDATE_EMPLOYEE_FAIL = 'UPDATE_EMPLOYEE_FAIL'

export const EMPLOYEE_DETAILS_REQUEST = 'EMPLOYEE_DETAILS_REQUEST'
export const EMPLOYEE_DETAILS_SUCCESS = 'EMPLOYEE_DETAILS_SUCCESS'
export const EMPLOYEE_DETAILS_FAIL = 'EMPLOYEE_DETAILS_FAIL'

export const NEW_COMMENT_REQUEST = 'NEW_COMMENT_REQUEST'
export const NEW_COMMENT_SUCCESS = 'NEW_COMMENT_SUCCESS'
export const NEW_COMMENT_RESET = 'NEW_COMMENT_RESET'
export const NEW_COMMENT_FAIL = 'NEW_COMMENT_FAIL'

export const DELETE_COMMENT_REQUEST = 'DELETE_COMMENT_REQUEST'
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS'
export const DELETE_COMMENT_RESET = 'DELETE_COMMENT_RESET'
export const DELETE_COMMENT_FAIL = 'DELETE_COMMENT_FAIL'

export const UPDATE_COMMENT_REQUEST = 'UPDATE_COMMENT_REQUEST'
export const UPDATE_COMMENT_SUCCESS = 'UPDATE_COMMENT_SUCCESS'
export const UPDATE_COMMENT_RESET = 'UPDATE_COMMENT_RESET'
export const UPDATE_COMMENT_FAIL = 'UPDATE_COMMENT_FAIL'

export const GET_COMMENTS_REQUEST = 'GET_COMMENTS_REQUEST'
export const GET_COMMENTS_SUCCESS = 'GET_COMMENTS_SUCCESS'
export const GET_COMMENTS_FAIL = 'GET_COMMENTS_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'